In [1]:
import numpy as np
import time

In [5]:
def array_creation():
    print("\n===== ARRAY CREATION =====")

    arr1 = np.array([1, 2, 3, 4, 5])
    arr2 = np.zeros((2, 3))
    arr3 = np.ones((3, 3))
    arr4 = np.arange(0, 10, 2)
    arr5 = np.linspace(0, 1, 5)
    arr6 = np.random.randint(1, 100, size=(3, 3))

    print("1D Array:", arr1)
    print("Zeros Array:\n", arr2)
    print("Ones Array:\n", arr3)
    print("Arange Array:", arr4)
    print("Linspace Array:", arr5)
    print("Random Integer Array:\n", arr6)

    return arr6
array_creation()



===== ARRAY CREATION =====
1D Array: [1 2 3 4 5]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Integer Array:
 [[52 47 26]
 [52 67 29]
 [53 70 52]]


array([[52, 47, 26],
       [52, 67, 29],
       [53, 70, 52]])

In [6]:
# 2. INDEXING AND SLICING
# -------------------------------------------------
def indexing_slicing(arr):
    print("\n===== INDEXING & SLICING =====")

    print("Original Array:\n", arr)
    print("Element at (0,1):", arr[0, 1])
    print("First Row:", arr[0])
    print("First Column:", arr[:, 0])
    print("Sliced (First 2 rows):\n", arr[:2, :])

    # Boolean indexing
    print("Elements > 50:", arr[arr > 50])

indexing_slicing(arr)


===== INDEXING & SLICING =====
Original Array:
 [[ 2 90 86]
 [13 98 10]
 [25 10 61]]
Element at (0,1): 90
First Row: [ 2 90 86]
First Column: [ 2 13 25]
Sliced (First 2 rows):
 [[ 2 90 86]
 [13 98 10]]
Elements > 50: [90 86 98 61]


In [9]:
# 3. MATHEMATICAL & STATISTICAL OPERATIONS
# -------------------------------------------------
def math_operations(arr):
    print("\n===== MATHEMATICAL OPERATIONS =====")

    print("Array:\n", arr)
    print("Sum:", np.sum(arr))
    print("Mean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))
math_operations(arr)


===== MATHEMATICAL OPERATIONS =====
Array:
 [[ 2 90 86]
 [13 98 10]
 [25 10 61]]
Sum: 395
Mean: 43.888888888888886
Median: 25.0
Standard Deviation: 37.24228315129173
Minimum: 2
Maximum: 98


In [10]:
# 4. AXIS-WISE OPERATIONS
# -------------------------------------------------
def axis_operations(arr):
    print("\n===== AXIS-WISE OPERATIONS =====")

    print("Column-wise Sum (axis=0):", np.sum(arr, axis=0))
    print("Row-wise Sum (axis=1):", np.sum(arr, axis=1))

    print("Column-wise Mean:", np.mean(arr, axis=0))
    print("Row-wise Mean:", np.mean(arr, axis=1))
axis_operations(arr)



===== AXIS-WISE OPERATIONS =====
Column-wise Sum (axis=0): [ 40 198 157]
Row-wise Sum (axis=1): [178 121  96]
Column-wise Mean: [13.33333333 66.         52.33333333]
Row-wise Mean: [59.33333333 40.33333333 32.        ]


In [14]:
# 5. RESHAPING & BROADCASTING
# -------------------------------------------------
def reshape_broadcast():
    print("\n===== RESHAPING & BROADCASTING =====")

    arr = np.arange(1, 13)
    print("Original 1D Array:", arr)

    reshaped = arr.reshape(3, 4)
    print("Reshaped to 3x4:\n", reshaped)

    # Flattening
    flattened = reshaped.flatten()
    print("Flattened Array:", flattened)
     # Broadcasting example
    vector = np.array([1, 2, 3, 4])
    print("Broadcast Addition:\n", reshaped + vector)
reshape_broadcast()


===== RESHAPING & BROADCASTING =====
Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Broadcast Addition:
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [17]:
# 6. SAVE & LOAD OPERATIONS
# -------------------------------------------------
def save_load_operations(arr):
    print("\n===== SAVE & LOAD OPERATIONS =====")

    # Save binary format
    np.save("saved_array.npy", arr)

    # Save text format
    np.savetxt("saved_array.txt", arr)

    # Load back
    loaded_npy = np.load("saved_array.npy")
    loaded_txt = np.loadtxt("saved_array.txt")

    print("Loaded from .npy:\n", loaded_npy)
    print("Loaded from .txt:\n", loaded_txt)
save_load_operations(arr)


===== SAVE & LOAD OPERATIONS =====
Loaded from .npy:
 [[ 2 90 86]
 [13 98 10]
 [25 10 61]]
Loaded from .txt:
 [[ 2. 90. 86.]
 [13. 98. 10.]
 [25. 10. 61.]]


In [19]:
# 7. PERFORMANCE COMPARISON
# -------------------------------------------------
def performance_comparison():
    print("\n===== PERFORMANCE COMPARISON =====")

    size = 1_000_000

    # Python List
    list_data = list(range(size))
    start = time.time()
    list_result = [x * 2 for x in list_data]
    list_time = time.time() - start

    # NumPy Array
    np_data = np.arange(size)
    start = time.time()
    np_result = np_data * 2
    np_time = time.time() - start

    print(f"Python List Time: {list_time:.6f} seconds")
    print(f"NumPy Array Time: {np_time:.6f} seconds")

    if np_time < list_time:
        print("NumPy is faster due to vectorization and optimized C backend.")

performance_comparison()



===== PERFORMANCE COMPARISON =====
Python List Time: 0.149026 seconds
NumPy Array Time: 0.004175 seconds
NumPy is faster due to vectorization and optimized C backend.
